source :rubygems
gem 'sinatra', '1.4.3'
gem 'json'
gem 'mysql2'
gem 'unicorn', '4.6.3'
gem 'dalli'
gem 'erubis',  '2.7.0'
gem 'foreman', '0.63.0'
gem 'mysql2-cs-bind', '0.0.6'
gem 'redis'
gem 'hiredis'
gem 'redcarpet'

group :development do
  # run "bundle exec shotgun" on development
  gem 'shotgun'
end
